### ISSUE TITLE
Declare and set Genesis Map final data

### ISSUE THREAD

**Issue by 1devNdogs** [offshoredao/theoffshore-web#5]
@heyoka404 Please, describe and load here the information related to the **genesis map collection** 

Collection

- [x] - Media Image 
- [x] - Name
- [x] - Description

NFT Metadata

- [x] - Name
- [x] - Media Image
- [x] - Description
- [x] - Background Color for OPENSEA
- [x] - External URL for OPENSEA

@heyoka404 if you want to add any traits (NFT) now is the moment. 
https://docs.opensea.io/docs/metadata-standards#attributes

**Comment by yoka404** [comment]
# Collection
Media Image
![emoji](https://user-images.githubusercontent.com/11360704/197303206-511f1395-9b71-4242-8a25-8a30b0d37373.png)


Name: Offshore 
Description:
We are a community-driven organization seeking to bring growth and abundance to its members.

# NFT 
Name: Offshore Genesis Map
Media image:

Static PNG
![offshore-genesis-map](https://user-images.githubusercontent.com/11360704/197303134-59b981d3-a214-4b00-a1b4-5c8dd6d139b7.png)

Media mp4 version:

https://user-images.githubusercontent.com/65098295/197274759-e7ebd7a8-afa2-49d3-abf3-1c95b759393d.mp4

Description: 
The Genesis Map gives holders lifetime citizenship to the Offshore DAO.
We are a community-driven organization seeking to bring growth and abundance to its members.

Background color OS:
#ffffff

Reference: 
<img width="383" alt="Screen Shot 2022-10-21 at 16 31 17" src="https://user-images.githubusercontent.com/65098295/197275128-344990dd-8287-41bb-af1a-ab33c4a7eeaf.png">


External URL for OS:
https://theoffshore.io/

Discord:
https://discord.gg/offshore

Twitter: 
https://twitter.com/offshoredao

Etherscan: 
?

Properties:
Duration: Lifetime
Rarity: Legendary

<img width="171" alt="Screen Shot 2022-10-21 at 16 23 45" src="https://user-images.githubusercontent.com/65098295/197273951-06ba8156-5de9-46d9-a2c1-81902a31ea51.png">

**Comment by 1devNdogs** [comment]
Will be creating batch csv  for batch mint. Ty

**Comment by yoka404** [comment]
Collection cover 1400x350

<img width="425" alt="collection-cover" src="https://user-images.githubusercontent.com/65098295/197285627-880229c7-9dcc-43dd-96df-724960d249f5.png">

**Comment by yoka404** [comment]
New Cover gif for the collection:

![palm1](https://user-images.githubusercontent.com/65098295/197300369-2230b5ef-897e-48a7-98c9-9827ce69fbe0.gif)

Testnet Collection:
https://testnets.opensea.io/collection/offshore-v3

**Comment by yoka404** [comment]
@1devNdogs mini text change in the NFT description:
added two words. "the and DAO"
New Description:
The Genesis Map gives holders lifetime citizenship to the Offshore DAO.
We are a community-driven organization seeking to bring growth and abundance to its members.
